<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Kolibri.Kino.Core\Kolibri.Kino.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="LiteDB" Version="5.0.21" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.12" />
    <PackageReference Include="MovieFileLibrary" Version="3.1.0" />
    <PackageReference Include="TMDbLib" Version="3.0.0" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Kolibri.Kino.Tests" />
  </ItemGroup>
</Project>