//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utilities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kolibri.Utilities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _new {
            get {
                object obj = ResourceManager.GetObject("_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;iso-8859-1&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:fo=&quot;http://www.w3.org/1999/XSL/Format&quot;&gt;
        ///  &lt;xsl:template match=&quot;/&quot;&gt;
        ///    &lt;html&gt;
        ///      &lt;HEAD&gt;
        ///        &lt;STYLE TYPE=&quot;text/css&quot;&gt;
        ///          .tabeller
        ///          {
        ///          background-position: center;
        ///          border: thin;
        ///          }
        ///          .bakgrunnsfarge
        ///          {
        ///          background-color: #B7DFE8;
        ///          }
        ///          .config
        ///          {
        ///          backgroun [rest of string was truncated]&quot;;.
        /// </summary>
        public static string altinn {
            get {
                return ResourceManager.GetString("altinn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] biztalk2013documenter {
            get {
                object obj = ResourceManager.GetObject("biztalk2013documenter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] biztalk2013images {
            get {
                object obj = ResourceManager.GetObject("biztalk2013images", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot;
        ///	xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;
        ///	xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot;
        ///	xmlns:user=&quot;http://www.sunaptic.com/xslt&quot;
        ///	exclude-result-prefixes=&quot;xsl msxsl user&quot; &gt;
        ///
        ///  &lt;!-- **********************************************************************************************
        ///	Title:			BizTalk Map Documenter Stylesheet (HTML Output)
        ///	Source:			http://biztalkmapdoc.codeplex.com/
        ///	Description:	This stylesheet is designed  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BizTalkMapDocumenterHTML {
            get {
                return ResourceManager.GetString("BizTalkMapDocumenterHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BringToFrontHS {
            get {
                object obj = ResourceManager.GetObject("BringToFrontHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CopyHS {
            get {
                object obj = ResourceManager.GetObject("CopyHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CutHS {
            get {
                object obj = ResourceManager.GetObject("CutHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dataset {
            get {
                object obj = ResourceManager.GetObject("dataset", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DocumentHS {
            get {
                object obj = ResourceManager.GetObject("DocumentHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsl:stylesheet version=&quot;1.0&quot;
        ///    xmlns=&quot;urn:schemas-microsoft-com:office:spreadsheet&quot;
        ///    xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; 
        /// xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot;
        /// xmlns:user=&quot;urn:my-scripts&quot;
        /// xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot;
        /// xmlns:x=&quot;urn:schemas-microsoft-com:office:excel&quot;
        /// xmlns:ss=&quot;urn:schemas-microsoft-com:office:spreadsheet&quot; &gt; 
        /// 
        ///&lt;xsl:template match=&quot;/&quot;&gt;
        ///  &lt;Workbook xmlns=&quot;urn:schemas-microsoft-com:office:spreadsheet&quot;
        ///    xmlns:o=&quot;urn:schemas-microso [rest of string was truncated]&quot;;.
        /// </summary>
        public static string excel {
            get {
                return ResourceManager.GetString("excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
        ///  &lt;xsl:output omit-xml-declaration=&quot;yes&quot; indent=&quot;yes&quot;/&gt;
        ///  &lt;!--&lt;xsl:strip-space elements=&quot;*&quot;/&gt;--&gt;
        ///  &lt;xsl:template match=&quot;/&quot;&gt;
        ///    &lt;style&gt;
        ///      body {font-family: sans-serif;}
        ///      td {padding: 4px;}
        ///    &lt;/style&gt;
        ///    &lt;table&gt;
        ///      &lt;xsl:apply-templates/&gt;
        ///    &lt;/table&gt;
        ///  &lt;/xsl:template&gt;
        ///  &lt;xsl:template match=&quot;*&quot;&gt;
        ///    &lt;tr&gt;
        ///      &lt;td style=&quot;background-color: #aaa;&quot;&gt;
        ///        &lt;p&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GenericHTML01 {
            get {
                return ResourceManager.GetString("GenericHTML01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
        ///  &lt;xsl:output omit-xml-declaration=&quot;yes&quot; indent=&quot;yes&quot;/&gt;
        ///  &lt;!--&lt;xsl:strip-space elements=&quot;*&quot;/&gt;--&gt;
        ///  &lt;xsl:template match=&quot;/&quot;&gt;
        ///    &lt;style&gt;
        ///      body {font-family: sans-serif;}
        ///      td {padding: 4px;}
        ///    &lt;/style&gt;
        ///    &lt;table&gt;
        ///      &lt;xsl:apply-templates/&gt;
        ///    &lt;/table&gt;
        ///  &lt;/xsl:template&gt;
        ///  &lt;xsl:template match=&quot;*&quot;&gt;
        ///    &lt;tr&gt;
        ///      &lt;td style=&quot;background-color: #aaa;&quot;&gt;
        ///        &lt;p&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GenericHTML01_attributes {
            get {
                return ResourceManager.GetString("GenericHTML01_attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap health_tests_512 {
            get {
                object obj = ResourceManager.GetObject("health_tests_512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] msxsl {
            get {
                object obj = ResourceManager.GetObject("msxsl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///  &lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
        ///
        ///  &lt;!-- Match the Base element, with high priority to avoid matching the more
        ///       specific template further down, that matches *[*] --&gt;
        ///  &lt;xsl:template match=&quot;Base&quot; priority=&quot;10&quot;&gt;
        ///    &lt;ul&gt;
        ///      &lt;xsl:apply-templates/&gt;
        ///    &lt;/ul&gt;
        ///  &lt;/xsl:template&gt;
        ///
        ///  &lt;!-- Match the Parent element, with high priority to avoid m [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ODXViewer_01 {
            get {
                return ResourceManager.GetString("ODXViewer_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
        ///  &lt;xsl:output omit-xml-declaration=&quot;yes&quot; indent=&quot;yes&quot;/&gt;
        ///  &lt;xsl:strip-space elements=&quot;*&quot;/&gt;
        ///
        ///
        ///  &lt;xsl:template match=&quot;/&quot;&gt;
        ///    &lt;style&gt;
        ///      body {font-family: sans-serif;}
        ///      td {padding: 4px;}
        ///    &lt;/style&gt;
        ///    &lt;table&gt;
        ///      &lt;xsl:apply-templates/&gt;
        ///    &lt;/table&gt;
        ///  &lt;/xsl:template&gt;
        ///
        ///  &lt;xsl:template match=&quot;*&quot;&gt;
        ///    &lt;tr&gt;
        ///      &lt;td style=&quot;background-color: #aaa;&quot;&gt;
        ///        &lt;p&gt;&lt;xsl [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ODXViewer_02 {
            get {
                return ResourceManager.GetString("ODXViewer_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap OpenFile {
            get {
                object obj = ResourceManager.GetObject("OpenFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap openHS {
            get {
                object obj = ResourceManager.GetObject("openHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon PageSetup {
            get {
                object obj = ResourceManager.GetObject("PageSetup", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PasteHS {
            get {
                object obj = ResourceManager.GetObject("PasteHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PrintHS {
            get {
                object obj = ResourceManager.GetObject("PrintHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PrintPreviewHS {
            get {
                object obj = ResourceManager.GetObject("PrintPreviewHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PrintSetupHS {
            get {
                object obj = ResourceManager.GetObject("PrintSetupHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap saveHS {
            get {
                object obj = ResourceManager.GetObject("saveHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SendToBackHS {
            get {
                object obj = ResourceManager.GetObject("SendToBackHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] specification {
            get {
                object obj = ResourceManager.GetObject("specification", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Ssms {
            get {
                object obj = ResourceManager.GetObject("Ssms", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap table {
            get {
                object obj = ResourceManager.GetObject("table", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///
        ///  &lt;xsl:output method=&quot;html&quot; indent=&quot;no&quot;/&gt;
        ///
        ///  &lt;!--
        ///  &lt;xsl:strip-space elements=&quot;*&quot;/&gt;
        ///--&gt;
        ///
        ///  &lt;xsl:param name=&quot;show_ns&quot;/&gt;
        ///  &lt;xsl:variable name=&quot;apos&quot;&gt;&apos;&lt;/xsl:variable&gt;
        ///
        ///  &lt;xsl:template match=&quot;/&quot;&gt;
        ///    &lt;html&gt;
        ///      &lt;head&gt;
        ///        &lt;STYLE TYPE=&quot;text/css&quot;&gt;
        ///          body       { font-family: sans-serif; font-size: 80%; background-color: #EAEAD9; color: black }
        ///
        ///          .connecto [rest of string was truncated]&quot;;.
        /// </summary>
        public static string treeview {
            get {
                return ResourceManager.GetString("treeview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///  &lt;xsl:output method=&quot;html&quot;/&gt;
        ///  &lt;xsl:template match=&quot;/&quot;&gt;
        ///    &lt;ul&gt;
        ///      &lt;xsl:apply-templates/&gt;
        ///    &lt;/ul&gt;
        ///  &lt;/xsl:template&gt;
        ///  &lt;xsl:template match=&quot;*&quot;&gt;
        ///    &lt;li&gt;
        ///      &lt;xsl:value-of select=&quot;name(.)&quot;/&gt;
        ///      &lt;xsl:if test=&quot;*&quot;&gt;
        ///        &lt;ul&gt;
        ///          &lt;xsl:apply-templates/&gt;
        ///        &lt;/ul&gt;
        ///      &lt;/xsl:if&gt;
        ///    &lt;/li&gt;
        ///  &lt;/xsl:template&gt;
        ///&lt;/xsl:stylesheet&gt;.
        /// </summary>
        public static string UnorderedList {
            get {
                return ResourceManager.GetString("UnorderedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;!--
        ///  Copyright (C) DSTC Pty Ltd (ACN 052 372 577) 2002
        /// 
        ///  The software contained on this media is the property of the
        ///  DSTC Pty Ltd.  Use of this software is strictly in accordance
        ///  with the license agreement in the accompanying LICENSE file.
        ///  If your distribution of this software does not contain a
        ///  LICENSE file then you have no rights to use this software
        ///  in any manner and should contact DSTC at the address below
        ///  to determine an  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string xs3p {
            get {
                return ResourceManager.GetString("xs3p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;xsl:transform xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;
        ///  version=&quot;1.0&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///               xmlns:b=&quot;http://schemas.microsoft.com/BizTalk/2003&quot;
        ///  exclude-result-prefixes=&quot;xs&quot;&gt;
        ///
        ///  &lt;xsl:output method=&quot;html&quot;/&gt;
        ///
        ///  &lt;xsl:template match=&quot;xs:attribute&quot; mode=&quot;attributes&quot;&gt;
        ///    &lt;tr valign=&quot;baseline&quot;&gt;
        ///      &lt;th align=&quot;left&quot; rowspan=&quot;2&quot;&gt;
        ///        &lt;xsl:value-of select=&quot;@name&quot;/&gt;
        ///      &lt;/th&gt;
        ///      &lt;td&gt;
        ///        &lt;xsl:choose&gt;
        ///          &lt;xsl:whe [rest of string was truncated]&quot;;.
        /// </summary>
        public static string xsd2html {
            get {
                return ResourceManager.GetString("xsd2html", resourceCulture);
            }
        }
    }
}
